
-- # TASK-3 # --

-- USE INVENTORY;

CREATE PROCEDURE ADDSUPPLIER @ID AS CHAR(5), @NAME AS VARCHAR(30), 
				 @ADDR AS VARCHAR(60), @CITY AS VARCHAR(30), 
				 @PHONE AS CHAR(14), @MAIL AS VARCHAR(60)
AS
BEGIN
	INSERT INTO SUPPLIER 
	VALUES (@ID, @NAME, @ADDR, @CITY, @PHONE, @MAIL);

	SELECT * FROM SUPPLIER
	WHERE SID = @ID;
END;

-- CHECKING THE CREATED PROCEDURES

ADDSUPPLIER 'S0001', 'DOT AND DASH ENGINEERING', 'No.13 Kishna nagar', 
			'CHENNAI', '8939157272','support@dnd.com';

--------------------

CREATE PROCEDURE ADDPRO @ID AS CHAR(5), @DESC AS VARCHAR(60), 
				 @PRICE AS INT, @CAT AS VARCHAR(30), @SID AS CHAR(5)
AS
BEGIN
	INSERT INTO PRODUCT
	VALUES (@ID, @DESC, @PRICE, @CAT, @SID);

	SELECT * FROM PRODUCT 
	WHERE PID = @ID;
END;

-- CHECKING THE CREATED PROCEDURES

ADDPRO 'P0001', 'IPHONE 11 PRO', 80000, 'ELECTRONICS', 'S0001';

--------------------

CREATE PROCEDURE ADDCUST @ID AS CHAR(5), @NAME AS VARCHAR(30),
				 @ADDR AS VARCHAR(70), @CITY AS VARCHAR(30),
				 @PHONE AS CHAR(14), @DOB AS DATE
AS
BEGIN
	INSERT INTO CUSTOMER
	VALUES (@ID, @NAME, @ADDR, @CITY, @PHONE, @DOB);

	SELECT * FROM CUSTOMER
	WHERE CID = @ID;
END;


-- CHECKING THE CREATED PROCEDURES

ADDCUST 'C0001', 'Krishna', 'No.44 vathalkalam street', 'Theni', 
		'8939152272', '09-11-1997';

--------------------

CREATE PROCEDURE ADDORDER @ID AS CHAR(5), @DATE AS DATE, @CID AS CHAR(5),
				 @PID AS CHAR(5), @QTY AS INT
AS
BEGIN
	INSERT INTO ORDERS
	VALUES (@ID, @DATE, @CID, @PID, @QTY);

	SELECT * FROM ORDERS
	WHERE OID = @ID;
END;

-- CHECKING THE CREATED PROCEDURES

ADDORDER 'O0001', '07-04-2021', 'C0001', 'P0001', 1;