
-- # TASK-2 # --

-- USE INVENTORY;

SELECT PRODUCT.PID, PDESC, CATEGORY, SNAME, SCITY
FROM PRODUCT
INNER JOIN SUPPLIER
ON PRODUCT.SID = SUPPLIER.SID;

--------------------

SELECT ORDERS.OID, ODATE, CNAME, CADDR, CPHONE, 
	   PDESC, PRICE, OQTY, (PRICE*OQTY) AS 'AMOUNT'
FROM ORDERS 
INNER JOIN CUSTOMER
ON ORDERS.CID = CUSTOMER.CID
INNER JOIN PRODUCT
ON ORDERS.PID = PRODUCT.PID;

--------------------

CREATE VIEW BILL
AS
	SELECT ORDERS.OID, ODATE, CNAME, CADDR, CPHONE,
	       PDESC, PRICE, OQTY, (PRICE*OQTY) AS 'AMOUNT'
	FROM ORDERS
	INNER JOIN CUSTOMER 
	ON ORDERS.CID = CUSTOMER.CID
	INNER JOIN PRODUCT
	ON ORDERS.PID = PRODUCT.PID;

-- CHECKING THE CREATED VIEW	
SELECT * FROM BILL;